$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: '0.2'
ignorePaths:
  ['.data', '.gitattributes', '.gitignore', '*.lock', '*-lock.yaml', 'prism.css', 'target']
dictionaryDefinitions: []
dictionaries: []
words: [
    # dev
    'blocklist',
    'noto',
    'oklab',
    'rslint',
    'safelist',
    'segoe',
    'taplo',
    # developers
    'akesson',
    'bram209',
    'carloskiki',
    'cinnog',
    'dande',
    'dandedotdev',
    'igorshubovych',
    'itehax',
    'kenji',
    'leohuynh',
    'makezu',
    'mayone',
    'miyazawa',
    'niklas',
    'rhysd',
    'Synphonyte',
    'tamasfe',
    'timlrx',
    'typicode',
  ]
ignoreWords: []
import: []
