# fly.toml app configuration file generated for dande-dev on 2025-02-23T21:04:01+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "dande-dev"
primary_region = "hkg"

[deploy]
strategy = "bluegreen"

[http_service]
auto_start_machines = true
auto_stop_machines = "stop"
force_https = true
internal_port = 8080
min_machines_running = 1

[[http_service.checks]]
grace_period = "10s"
interval = "30s"
method = "GET"
path = "/"
timeout = "5s"

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 256
