name: Check Secrets

on:
  pull_request:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  check-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v6

      - name: Install Git Secrets
        run: |
          sudo apt-get update -y
          sudo apt-get install -y git-secrets

      - name: Scan for secrets
        run: |
          git secrets --register-aws
          git secrets --scan
